advanced_user/advanced_user/urls.py
from django.urls.conf import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_auth.urls')),
]

advanced_user/user_auth/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = 'User'

urlpatterns = [
    path('', views.home_view, name="home"),
    path('logout/', views.logout_view, name="logout"),
    path('login/', views.login_view, name="login"),
    path('signup/', views.signup_view, name="signup"),
    path('sent/', views.activation_sent_view, name="activation_sent"),
    path('activate/<slug:uidb64>/<slug:token>/', views.activate, name='activate'),
]

advanced_user/user_auth/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100, blank=True)
    last_name = models.CharField(max_length=100, blank=True)
    email = models.EmailField(max_length=150)
    bio = models.TextField()
    signup_confirmation = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

@receiver(post_save, sender=User)
def update_profile_signal(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

advanced_user/user_auth/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=100 ,label='Enter FirstName')
    last_name = forms.CharField(max_length=100 ,label='Enter LastName')
    email = forms.EmailField(max_length=150, help_text='Enter your Email')
    bio = forms.CharField(max_length=200,widget=forms.Textarea(attrs={'rows':3}) , help_text='Describe yourself')


    class Meta:
        model = User
        fields = ('first_name', 'last_name','username','email', 'password1', 'password2','bio')

advanced_user/user_auth/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_text,force_bytes
from django.utils.http import urlsafe_base64_decode,urlsafe_base64_encode
from django.urls import reverse
from django.db import IntegrityError
from django.contrib.auth.models import User
from .forms import SignUpForm
from .models import Profile
from .tokens import account_activation_token
from django.template.loader import render_to_string


def home_view(request):
    if request.user.is_authenticated:
        return render(request, 'user/index.html',{'loggedin':True})
    return render(request, 'user/index.html',{'loggedin':False})

def activation_sent_view(request):
    return render(request, 'user/activation_sent.html')


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    # checking if the user exists, if the token is valid.
    if user is not None and account_activation_token.check_token(user, token):
        # if valid set active true 
        user.is_active = True
        # set signup_confirmation true
        user.profile.signup_confirmation = True
        user.save()
        login(request, user)
        return HttpResponseRedirect(reverse('User:home'))
        # return redirect('home')
    else:
        return render(request, 'user/activation_invalid.html')


def signup_view(request):
    form = SignUpForm(request.POST)
    if form.is_valid():
        # form.save()
        # username = form.cleaned_data.get('username')
        # password = form.cleaned_data.get('password1')
        # user = authenticate(username=username, password=password)
        user = form.save()
        user.refresh_from_db()
        user.profile.first_name = form.cleaned_data.get('first_name')
        user.profile.last_name = form.cleaned_data.get('last_name')
        user.profile.email = form.cleaned_data.get('email')
        user.profile.bio = form.cleaned_data.get('bio')
        # user can't login until link confirmed
        user.is_active = False
        user.save()
        current_site = get_current_site(request)
        print(current_site)
        subject = 'Please Activate Your Account'
        # load a template like get_template() 
        # and calls its render() method immediately.
        message = render_to_string('user/activation_request.html', {
            'user': user,
            'domain': current_site.domain,
            'uid': urlsafe_base64_encode(force_bytes(user.pk)),
            # method will generate a hash value with user related data
            'token': account_activation_token.make_token(user),
        })
        # print(message)
        user.email_user(subject, message)
        return HttpResponseRedirect(reverse('User:activation_sent'))
        # return redirect('activation_sent')
        # user.save() # post_save function at models.py triggers here
        # username = form.cleaned_data.get('username')
        # password = form.cleaned_data.get('password1')
        # login(request, user)
        # user = authenticate(username=username, password=password)
    else:
        # form = SignUpForm()
        return render(request, 'user/signup.html', {'form': form})
        
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('User:signup'))

def login_view(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('User:home'))

    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username = username,password = password)
        if user is not None:
            login(request,user)
            return HttpResponseRedirect(reverse('User:home'))
        else:
            form = AuthenticationForm()
            return render(request,'user/login.html',{'form' : form,"message":"Invalid Credentials"})
    form = AuthenticationForm()
    return render(request,'user/login.html',{'form' : form})
        

advanced_user/user_auth/templates/user/activation_request.html
{% autoescape off %}
Hi {{ user.username }},

Please click the following link to confirm your registration:

http://{{ domain }}{% url 'User:activate' uidb64=uid token=token %}
{% endautoescape %}

advanced_user/user_auth/templates/user/activation_sent.html
Activation link sent! Please check your console.

advanced_user/user_auth/templates/user/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {%if loggedin%}
        <h1>Logged IN</h1>
        <h1>
            {{request.user.username}}
        </h1>
        <p>
            {{request.user.first_name}}
            {{request.user.last_name}}
        </p>
        <br>
        <p>
            {{request.user.profile.bio}}
            {{request.user.profile.email}}
        </p>
        <a href="{%url 'User:logout'%}">LogOut</a>
    {%else%}
        <h1>Logged Out</h1>
        <a href="{%url 'User:login'%}">Login</a>
        <a href="{%url 'User:signup'%}">SignUp</a>
    {%endif%}
</body>
</html>

advanced_user/user_auth/templates/user/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {%if message%}
        <p>{{message}}</p>
    {%endif%}
    <form action="{%url 'User:login'%}" method="POST">
        {%csrf_token%}
        {%for field in form%}
            <p>
            {{ field.label_tag }}<br>
            {{ field }}
            {% if field.help_text %}
              <small style="color: grey">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
              <p style="color: red">{{ error }}</p>
            {% endfor %}
            </p>
        {%endfor%}
        <input type="submit" value="submit">
    </form>

</body>
</html>

advanced_user/user_auth/templates/user/signup.html
<h2>Sign up</h2>
<form method="post">
  {% csrf_token %}
  {% for field in form %}
    <p>
      {{ field.label_tag }}<br>
      {{ field }}
      {% if field.help_text %}
        <small style="color: grey">{{ field.help_text }}</small>
      {% endif %}
      {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
      {% endfor %}
    </p>
  {% endfor %}
  <button type="submit">Sign up</button>
</form>